version: '3.4'

services:
  redis:
    image: redis:alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    ports:
      - 6380:6379
volumes:
  redis-data: